---
- name: Configure Monit (Debian)
  ansible.builtin.include_vars: debian.yml
  when: ansible_os_family == "Debian"

- name: Configure Monit (RedHat)
  ansible.builtin.include_vars: redhat.yml
  when: ansible_os_family == "RedHat"

- name: Create includes folder
  ansible.builtin.file:
    path: "{{ monit_includes }}"
    state: directory
    mode: "0600"

- name: Create lib folder
  ansible.builtin.file:
    path: "{{ monit_lib_folder }}"
    state: directory
    mode: "0600"

- name: Setup monitrc
  ansible.builtin.template:
    src: monitrc.j2
    dest: "{{ monitrc_conf }}"
    owner: root
    group: root
    mode: "0700"
  notify: restart monit

- name: Setup webinterface
  ansible.builtin.template:
    src: webinterface.j2
    dest: "{{ monit_includes }}/webinterface"
    owner: root
    group: root
    mode: "0644"
  notify: restart monit

- name: Setup mail alerts
  ansible.builtin.template:
    src: mail.j2
    dest: "{{ monit_includes }}/mail"
    owner: root
    group: root
    mode: "0644"
  notify: restart monit
  when: monit_mail_enabled
