---
- name: Setup mail alerts
  ansible.builtin.template:
    src: mail.j2
    dest: "{{ monit_includes }}/mail"
    owner: root
    group: root
    mode: "0644"
  notify: restart monit
  when: monit_mail_enabled
