---
- name: Monit - Write monitors
  ansible.builtin.template:
    src: monitor.j2
    dest: "{{ monit_includes }}/{{ item.name }}"
    owner: root
    group: root
    mode: "0600"
  with_items: "{{ monit_services }}"
  notify: restart monit

- name: Monit - Create facts directory
  ansible.builtin.file:
    path: "/etc/ansible/facts.d"
    mode: "0755"
    state: directory

- name: Monit - Registers configured monitors
  ansible.builtin.template:
    src: "monit.fact.j2"
    dest: "/etc/ansible/facts.d/monit.fact"
    mode: "0600"
  register: monit_write_facts

- name: Monit - Reload facts
  ansible.builtin.setup:
    filter: "ansible_local"
  when: monit_write_facts.changed

- name: Monit - List configured monitors
  ansible.builtin.command: ls -1 {{ monit_includes }}
  register: monit_services_present
  changed_when: false

- name: Monit - Remove unused monitors
  ansible.builtin.file:
    path: "{{ monit_includes }}/{{ item }}"
    state: absent
  with_items: "{{ monit_services_present.stdout_lines | default([]) }}"
  when: monit_service_delete_unlisted and item|basename not in ansible_local.monit.monit_configured_services
  notify: restart monit
